server.port=9000
spring.application.name=live26
spring.datasource.url=jdbc:postgresql://database-docker:5432/live26database
spring.datasource.username=live26user
spring.datasource.password=live26password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
frontend.url=http://localhost:3000